### ISSUE TITLE
i see this error. When use lighthouse ^3.5 

### ISSUE THREAD

**Issue by TrustNguyen** [joselfonseca/lighthouse-graphql-passport-auth#11]
i see this error. When use lighthouse ^3.5 
{
  "errors": [
    {
      "message": "Schema is not configured for mutations.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}

**Comment by joselfonseca** [comment]
hello @TrustNguyen, please add a mutation to your schema, I need to update the docs but it expects that at least one mutation is created to be able to extend the type. I will also look into another possibility so that is now necessary, but that is error should go away if you add at least one mutation to your schema

**Comment by TrustNguyen** [comment]
Thank you!, I have an error when using the default, I will customize it again. Hope you will soon release specific documents.

**Comment by joselfonseca** [comment]
Add Documentation for newly created projects.

**Comment by joselfonseca** [comment]
Here is a tutorial for this 
https://ditecnologia.com/2019/06/24/graphql-auth-with-passport-and-lighthouse-php/
