### ISSUE TITLE
PHPUnit testing Authentication

### ISSUE THREAD

**Issue by imd-solutions** [joselfonseca/lighthouse-graphql-passport-auth#20]
Hi,

Thanks for your response with the other PHPUnit Testing issue I raised. I worked something out that is doing the trick. I will try not to ask anymore questions after this... I hope.

I have tried testing the authentication process with PHPUnit.  I have managed to test all mutations apart from the logout.

$this->mutation('logout', ['status', 'message']); logout = the mutation, [status and message] = the LogoutResponse payload

When I run that, I get the below error message:

“message” => “Syntax Error: Expected Name, found Int”

It would seem that it is asking for a second parameter (Which I am guessing is the Authorization Bearer info), but in the schema, there are no parameters, just the payload:

Schema: logout: LogoutResponse!

Would appreciate a stir in the right direct.

**Comment by joselfonseca** [comment]
Hello, not sure why you are testing this again because this is already tested in the package, take a look at https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/tests/Integration/GraphQL/Mutations/Logout.php and also the full test suite https://github.com/joselfonseca/lighthouse-graphql-passport-auth/tree/master/tests/Integration/GraphQL/Mutations

IF you want to test it again is OK but keep in mind that this was tested already and may not be necessary unless you change the resolvers and implement custom logic.
