### ISSUE TITLE
Exception: Undefined index: Mutation

### ISSUE THREAD

**Issue by francisco-ltech** [joselfonseca/lighthouse-graphql-passport-auth#25]
Hi,

This error is showing up in the Laravel.log file after a fresh install of the package:

Undefined index: Mutation {"exception":"[object] (ErrorException(code: 0): Undefined index: 
Mutation at /Users/.../vendor/nuwave/lighthouse/src/Schema/AST/ASTBuilder.php:148)

Using:
"joselfonseca/lighthouse-graphql-passport-auth": "^1.4",
"mll-lab/laravel-graphql-playground": "^1.1",
"nuwave/lighthouse": "^4.2"

Am I missing something?

**Comment by joselfonseca** [comment]
hello there, 

you need to have a Mutation at least declared on the schema since the package tries to extend that Type, if you don't have one it will show that error. I think I explained that here

https://dev.to/joselfonseca/graphql-auth-with-passport-and-lighthouse-php-14g5

you can also publish the config and update the path to have full control over the schema being used.

**Comment by francisco-ltech** [comment]
Perfect, thank you!
