### ISSUE TITLE
[Enhancement] Email Verification in Registration

### ISSUE THREAD

**Issue by gcloares** [joselfonseca/lighthouse-graphql-passport-auth#37]
Any plans on adding email verification in the registration part? Thanks!

**Comment by joselfonseca** [comment]
Hello @gcloares 

Thanks for the Feature request, I did not have any plans as we don't use it much in our projects, but I think is something we can look into as part of 2.1 release. 

I'll find some time to work on this or maybe someone submits a PR with it.

**Comment by locent217** [comment]
I tried using username to on login instead of email. but it shows "credentials were incorrect"

**Comment by joselfonseca** [comment]
@locent217 hello there, please aso look at Passport's documentation about it. 

https://laravel.com/docs/6.x/passport#customizing-the-username-field

You need to also make sure Passport is configured properly for the use case. Also please next time create a separated issue for this as this issue is about email verification and not this.

**Comment by joselfonseca** [comment]
Implemented here https://github.com/joselfonseca/lighthouse-graphql-passport-auth/pull/52

**Comment by joselfonseca** [comment]
Released with a breaking change https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/3.0.0
