### ISSUE TITLE
the @auth is not working to return the authenticated user

### ISSUE THREAD

**Issue by herbertpimentel** [joselfonseca/lighthouse-graphql-passport-auth#43]
using the @auth is not working to return the authenticated user

```
type Query {
 me: User @auth
 ...
}
```

```
{
   "Authorization": "Bearer <token returned from login here>"
}
```

**Comment by joselfonseca** [comment]
Hello there, It currently works on several projects where we use it. Can you please be a little more specific of the error you get or the response. 

Thanks.

**Comment by herbertpimentel** [comment]
Thanks for the quick answer, actually there's no error, I am trying out the stack. laravel + lighthouuse + passport + this, and I am follwoing this tutorial, in the end, everything is working as expected... login mutation, protected mutation with the middleware... but this @auth returns null instead of the user as i was expecting.

**Comment by joselfonseca** [comment]
This is how we use it

```
me: User! @auth @middleware(checks: ["auth:api"])
```

You need to apply the Auth middleware since Passport has to set up the currently logged in user by token. Also that will protect the query to be executed only on authenticated requests. the Auth directive takes the logged in user and returns it but does not set it from the authentication method. That is what the other Middleware does.

**Comment by joselfonseca** [comment]
You could also use the directive like this 

```
type Query {
    me: User @auth(guard: "api")
}
``` 

https://lighthouse-php.com/4.7/api-reference/directives.html#auth
