### ISSUE TITLE
How To Login with Both Email and Phone Number

### ISSUE THREAD

**Issue by ockba-a** [joselfonseca/lighthouse-graphql-passport-auth#59]
I want to Login with Both Email and Phone Number when change in config   
    
   ` 'username' => 'email' `

I can only access by Email and Error when I try access by Phone Number as following

> "debugMessage": "No query results for model [App\\User].",
>       "message": "Internal server error",
>       "extensions": {
>         "category": "internal"

And change the 

` username' => 'phone_num' `

I can only access by Phone Number and Error when I try access by Email same error as above.
 
So any idea

I try to add the 
 
` username' => ['phone_num','email'] `

> 
> "errors": [
>     {
>       "debugMessage": "SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause' (SQL: select * from `users` where (`0` = email and `1` = phone_num) limit 1)",
>       "message": "Internal server error",
>       "extensions": {
>         "category": "internal"
>       },

**Comment by joselfonseca** [comment]
@ockba-a hello there, it will not work as an array, currently using 2 columns to identify the user is not supported. I am not sure if passport supports that.

**Comment by joselfonseca** [comment]
You will have to use a different resolver to grant the tokens and do the verifications you need there.

**Comment by ockba-a** [comment]
> @ockba-a hello there, it will not work as an array, currently using 2 columns to identify the user is not supported. I am not sure if passport supports that.

@joselfonseca Thank you for reply, 

Let me Check and I will reply ASAP.

**Comment by benxmy** [comment]
@ockba-a - were you able to make it work? We just came across the same requirement...

**Comment by joselfonseca** [comment]
@benxmy In order to support this I think we need to not just customize Laravel Passport authentication but also change the request this package does. 

So What I would do first is I would check in passport how to support this. I guess a custom grant can do the job and then you would just modify the login mutation to make the request with that specific grant instead of the password grant. 

Basically you would change this method https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/Login.php#L22 to use the new grant

The socialite integration does this, can be used as an example. 

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/SocialLogin.php#L26

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/OAuthGrants/SocialGrant.php

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/HasSocialLogin.php#L22

I am not sure if this is common enough to support it in the package.

**Comment by benxmy** [comment]
@joselfonseca - Yeah, I'm currently kind of down the rabbit hole in passport. I'll take a look at those links.  I do think it's a corner-case...If I come up with a reasonable solution I'll post it. Was hoping someone might have figured out a simple work-around and saved me some time!

**Comment by joselfonseca** [comment]
@benxmy I think the way to go here is a custom grant. Def take a look at how I implemented a custom grant for the social login. That can be your solution. You just need to point your resolver to a custom one that extends the one on this package and pass the second argument to the buildCredentials method to use your custom grant.

**Comment by joselfonseca** [comment]
Closing this as is not a use case for the package. Any questions or if anyone needs help with this please open a new PR or contact me on Lighthouse's slack channel.

**Comment by silasrm** [comment]
Hi,

Try to implement _findForPassport_ in your authentication model checking value in both fields?

```php
    public function findForPassport($username) {
        return $this->query()->where('phone', $username)->orWhere('email', $username)->first();
    }
```

See: https://laravel.com/docs/7.x/passport#customizing-the-username-field

**Comment by ranjitappminds** [comment]
> ```
> return $this->query()->where('phone', $username)->orWhere('email', $username)->first();
> ```

it worked thanks 👍
