### ISSUE TITLE
Register : rsp all null

### ISSUE THREAD

**Issue by MilesWuCode** [joselfonseca/lighthouse-graphql-passport-auth#62]
Register : rsp all null.
Is normal ？

![image](https://user-images.githubusercontent.com/1192835/73640879-04f87d80-46aa-11ea-9848-b7a23e59cc48.png)

**Comment by joselfonseca** [comment]
If you upgraded to 3.0 there is a breaking change I posted here

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/3.0.0

since we now support email verification, you have to update the schema to this 

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/graphql/auth.graphql#L41-L44

If you are not using the email verification feature in laravel it will give you the tokens under the tokens property without requesting email verification.

**Comment by MilesWuCode** [comment]
Nice , This is great tool !!
