### ISSUE TITLE
SocialLogin - RequestGuard::onceUsingId does not exist

### ISSUE THREAD

**Issue by a-zog** [joselfonseca/lighthouse-graphql-passport-auth#82]
Hi,

First of all, thank you for this package, it's very helpful.

I've tried to use the social login GQL query as mentioned in the documentation.
https://lighthouse-passport-auth.web.app/docs/default-schema/

But I've got this error:
`"message": "Method Illuminate\\Auth\\RequestGuard::onceUsingId does not exist."`
at: HasSocialLogin.php > Auth::onceUsingId($user->id)

I found that it would work with `Auth::guard('web')->onceUsingId($user->id)` but then it would not sync with `SocialLogin@solve` because it's still using the default guard (API).

This is a preview of the api middlewares used:

```
 protected $middlewareGroups = [
         ...
        'api' => [
            'throttle:60,1',
            'bindings',
            \Barryvdh\Cors\HandleCors::class,
            \App\Http\Middleware\UseApiAuthGuard::class,
        ],
];
```

I may doing it wrong. I would appreciate some guidance if it were the case.

Thank you in advance

**Comment by joselfonseca** [comment]
Is web your default guard?

**Comment by a-zog** [comment]
API is set to be the default

**Comment by joselfonseca** [comment]
yeah, that may be the problem, We actually never set the default to api so maybe that is why I never encounter this error. We have 2 options here.

1. Set the default back to web and use `guard(with: ['api'])` (this is what we usually do)
2. Override the trait method and use the `Auth::guard('web')->onceUsingId($user->id)` This is done just because we need to set the logged in user to retreive it later in the pipeline. 

I still want to see a better way to do this but for now these would be the options.

**Comment by a-zog** [comment]
Okey, thank you for your help

**Comment by joselfonseca** [comment]
no problem, closing this.

**Comment by rushairer** [comment]
I have the same problem.

How to fix this bug? 

Thanks! @joselfonseca

**Comment by joselfonseca** [comment]
Hi @rushairer is not actually a bug, but in the latest version I changed that to use another method to set the user. you can update to latest keeping in mind there is a breaking change in how social login works, or override the method and use Auth::setUser()

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/HasSocialLogin.php#L53

**Comment by rushairer** [comment]
@joselfonseca Thanks!
I am updating my packages.
